### ISSUE TITLE
Make django badgekit client

### ISSUE THREAD

**Issue by davidascher** [mozilla/mozbadging#12]

**Comment by andrewhayward** [comment]
The hards bits of this are done: see [badgekit-api-python-client](/mozilla/badgekit-api-python-client).

Various routes are still to be done, but these can be done as and when needed.

**Comment by emgollie** [comment]
@andrewhayward working to make this Mozillians.org feature complete per our team meeting on 1 July.

**Comment by andrewhayward** [comment]
This exists, but isn't 100% feature-complete. @christensenep reckons it's got enough coverage for mozillians.org to work, so closing this with the assumption that should we need to do work on it in the future we can open specific tickets.
