### ISSUE TITLE
Setup andrew so that he can push changes to badges.m.o.

### ISSUE THREAD

**Issue by davidascher** [mozilla/mozbadging#19]
cmore sez:

I would file a webops bug:

https://bugzilla.mozilla.org/enter_bug.cgi?product=Infrastructure%20%26%20Operations&component=WebOps%3A%20Other

CC: lcrouch@mozilla.com and lorchard@mozilla.com

I would reference the bugs below that I mentioned about Chief that was setup on badges. They also need to know who needs to have access to deploy to stage/production. I would keep Less in the loop since he built the site and can probably provide additional guidance.

Is there a developer with playdoh experience and has VPN access with their ldap? Check out this bug as it is very similar request:

https://bugzilla.mozilla.org/show_bug.cgi?id=1017519

**Comment by davidascher** [comment]
Andrew, if you need VPN access to MPT, go to service-now.

**Comment by andrewhayward** [comment]
Opened a bug here: https://bugzilla.mozilla.org/show_bug.cgi?id=1035431

**Comment by andrewhayward** [comment]
I already have access to VPN, and @lmorchard has sent me some credentials via email. Will see if they still work!

**Comment by andrewhayward** [comment]
This all seems to work. Closing.
