### ISSUE TITLE
Establish baseline data for badges.m.o (via GA)

### ISSUE THREAD

**Issue by adamlofting** [mozilla/mozbadging#21]
- [ ] Get access to existing account
- [ ] Gather available baseline metrics
- [ ] Scope additional tracking if required (GA Events, Goals, Search etc)

**Comment by adamlofting** [comment]
GA Access requested for us here: https://bugzilla.mozilla.org/show_bug.cgi?id=1024429

**Comment by adamlofting** [comment]
The existing GA tracking code on badges.m.o is actually from another site: http://badg.us which seems to be a copy/paste of the badges software - but it's not clear who owns or runs that site. 
@emgollie @davidascher  - do you know anything about http://badg.us ?

I'll carry on on the assumption that badges.m.o has no GA history and we're going to have to create a profile and start tracking this now.

**Comment by emgollie** [comment]
@adamlofting That site was also created by @lmorchard: https://github.com/lmorchard/badg.us

**Comment by adamlofting** [comment]
I'm closing this as there isn't baseline data, but the task of getting some is in progress. I'll file a separate task for setting up event and goal tracking in the new GA.

**Comment by emgollie** [comment]
Sounds good, thanks @adamlofting.

**Comment by lmorchard** [comment]
Just saw this issue... FWIW, badg.us is now hosted & maintained by Mozilla Community IT - https://github.com/Mozilla-cIT/badg.us
