### ISSUE TITLE
Weekly progress updates from team

### ISSUE THREAD

**Issue by emgollie** [mozilla/mozbadging#22]
We mentioned doing an asynchronous check-in towards the tail end of the week. I can kick it off each Thursday (and am open to email updates if we don't want these in GitHub).
- [X] Grow Mozilla roadmap sharing and feedback solicitation
- [ ] Surveys and interviews with internal stakeholders to plan badges.m.o. site pages
- [ ] Badge studio design brief for issuers brainstorm
- [ ] Determining UI process with @zzzndr

Over to you @andrewhayward @christensenep @adamlofting @davidascher.

**Comment by emgollie** [comment]
Also, we can make part of our check-in on Tuesday a retro about our first heartbeat milestone tomorrow.

**Comment by adamlofting** [comment]
Thanks for the reminder :+1: 
- [x] Review @christensenep 's PR that counts badges issued in adhoctribution 
- [x] #6 Decide _how_ to integrate contribution dashboards into mozbadges metrics 
- [x] Start process for adding Google Analytics to badges.m.o

Missed the (heart)beat:
- [ ] Decide how to allocate a badge to a particular team or contribution type for reporting purposes #8

**Comment by emgollie** [comment]
@christensenep @andrewhayward Friendly check-in on this. Tomorrow we will also discuss live via https://openbadges.etherpad.mozilla.org/mozbadges.

**Comment by ghost** [comment]
Hello!  Sorry I am late on this.
- [x] Adhoctribution PR that logs earners of specified badges as contributors
- [x] Staging version of badges.m.o deployed
- [ ] Refactor badges.mozilla.org to use the django badgekit client

I'm working on getting the staging version of badges.m.o up and running in heroku, should be done by our meeting tomorrow.  badges.mozilla.org using the django badgekit client will miss the heartbeat, unfortunately.

**Comment by andrewhayward** [comment]
Sorry, missed this.
- [ ] BadgeKit API python client
  - [x] Testing framework
- [ ] Working through VPN/Chief setup

The API client has proven to be a lot more legwork than I was anticipating. The hard work is done, but it might be a case of filling in bits as and when we need them.

I'm also quite confused as to what the Webmaker guys are waiting on us for. [This bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1004565) is asking that we "move to action [it] ASAP", but I don't know what they're actually after.

Finally, slowly wading my way through what I need to do to get access to the badges.m.o chief config.
