### ISSUE TITLE
Weekly progress updates from team 

### ISSUE THREAD

**Issue by emgollie** [mozilla/mozbadging#28]
Kicking off our end-of-week note to share these updates:
- Analyzing conversations with internal users to identify major needs for badges.m.o.: https://github.com/mozilla/mozbadging/issues/27
- Met with @zzzndr to discuss sitemap, wireframes, and design themes. Will have initial ideas to share on Tuesday's call.
- Adam hosted a conversation about counting contributors with possible routes moving forward: https://etherpad.mozilla.org/counting-contributors-with-badges

Over to you @christensenep (curious to hear how Sara is doing) @andrewhayward @adamlofting @davidascher. Thanks all.

**Comment by adamlofting** [comment]
- The meeting notes you've linked to.
- GA account is ready but we need to update prod to get baseline data #29 
- In related news, central mozilla contributor dashboards are now here: http://areweamillionyet.org based on data in Baloo. So I'll start thinking about how the data connects from mozbadges to Baloo

**Comment by ghost** [comment]
- bmo.herokuapp.com is up and running
- Working on converting bmo/django-badger to talk to badgekit api using @andrewhayward's https://github.com/mozilla/badgekit-api-python-client library

**Comment by emgollie** [comment]
@andrewhayward, let us know if there is anything we should review before tomorrow (agenda is open for additions: https://openbadges.etherpad.mozilla.org/mozbadges; we'll also be reviewing @zzzndr's initial UI ideas). Thanks all.

**Comment by andrewhayward** [comment]
@emgollie - oops, missed this again.
- Made some big steps in getting the Sandstone theme into badges.m.o
  - Need to talk to @christensenep about getting this onto [bmo.heroku](http://bmo.herokuapp.com)
  - Evidently there's some discussion to be had around @zzzndr's wireframes
- Talked to @christensenep about possible ways of integrating the badge studio into the creation workflow. No code written for this yet, but I think I know where I'm going with it.
