### ISSUE TITLE
Adding GA to existing badges.m.o so we can establish baseline numbers

### ISSUE THREAD

**Issue by adamlofting** [mozilla/mozbadging#29]
I have a [GA tracking tag](https://bugzilla.mozilla.org/show_bug.cgi?id=1024429) for us to add into the existing badges.m.o site to gather some baseline metrics.

@davidascher @christensenep @andrewhayward - do we have access to make changes? Or should I file this somewhere else for now?

**Comment by andrewhayward** [comment]
We don't, but the MozBadges team should probably be given access to the repository. Once we can push code through though, we can conceptually update the site. (Note to self...)

**Comment by adamlofting** [comment]
I will ask Chris about how to get this in place with minimal work on the existing platform.

**Comment by adamlofting** [comment]
Ticket opened for this: https://bugzilla.mozilla.org/show_bug.cgi?id=1030046

**Comment by adamlofting** [comment]
@andrewhayward is merging and pushing this something we're setup to do now? 
https://github.com/mozilla/badges.mozilla.org/pull/71

**Comment by andrewhayward** [comment]
@adamlofting - in theory this is something we're set up to do now, yes. We have the tools to do it. I'm just not quite sure how to use them :)

Need to talk to @lmorchard.

**Comment by andrewhayward** [comment]
I've merged [`badges.mozilla.org#71`](https://github.com/mozilla/badges.mozilla.org/pull/71). In theory, [the `dev` box](https://badges-dev.allizom.org/) should auto-update, so I'm going to keep an eye on that for a while. If it does, then I think I know what I'm doing as regards deploying to staging/master. Will keep you posted.

**Comment by andrewhayward** [comment]
@adamlofting - `dev` has now updated itself, as I hoped it might, so you should at some point (if not already) see a hit in Google Analytics for the new code. I've seemingly successfully deployed to `staging` too (in so much as it reported a success), but I'm yet to see the results of that on [the `staging` box](https://badges.allizom.org/). That might just be a case of more persistent caching, but I'll let you know.

**Comment by andrewhayward** [comment]
Spoke too soon. `staging` is now showing the same changes. As and when you see some information in GA that looks correct, let me know and I'll push the change live.

**Comment by adamlofting** [comment]
This is firing correctly on staging and is not causing any JS errors, but this doesn't show in GA yet because the traffic is filtered to only report on `badges.mozilla.org` domain.

As we don't have any existing tracking to break by getting this wrong. I suggest this is ready to push live :)

**Comment by andrewhayward** [comment]
Pushed to production.
