### ISSUE TITLE
End of week team check in

### ISSUE THREAD

**Issue by emgollie** [mozilla/mozbadging#33]
Hi all, wanted to check in to see how we're tracking against today's heartbeat. A few updates:
- [x] Collaboration with @zzzndr underway on distinguishing earner and issuer flows.
- [ ] Undertaking wiki migration for visual badge info listed in org doc.
- [ ] Need to check in with @adamlofting w.r.t. https://github.com/mozilla/mozbadging/issues/32.

Over to you @andrewhayward @christensenep @davidascher.

**Comment by emgollie** [comment]
We'll plan to meet here on Tuesday to talk about the heartbeat and this week's progress: https://openbadges.etherpad.mozilla.org/mozbadges

cc @andrewhayward @christensenep @zzzndr @adamlofting (@davidascher is out on Tuesday for a Canadian holiday but we'll debrief him after).

**Comment by adamlofting** [comment]
Only one update from me this week:
- Pull request is open for: Adding GA to existing badges.m.o so we can establish baseline numbers #29

**Comment by andrewhayward** [comment]
Sorry, missed this... _again_.
- [x] Re-skinned current badges.m.o to Sandstone
- [x] Added badge studio into creation workflow

Will talk to Erik and see if we can get this up on a box somewhere for people to look at.

![make-a-badge](https://cloud.githubusercontent.com/assets/159848/3443602/d966e34e-0124-11e4-80d6-2617b1ccf2ac.gif)

Didn't get a chance to look into VPN/box access. Need to prioritise that for this coming sprint.

**Comment by ghost** [comment]
I'm working on deploying it now. :)

I'm attempting to integrate it with what I've got ready for the badgekit api integration stuff.  Unfortunately I do still have work to do here (some of it likely on our own branch of badgekit api), but you can create, edit, and delete badgekit badges now (though you can't award them yet).  (PR is here https://github.com/mozilla/mozilla-badges/pull/4)
