### ISSUE TITLE
End of week team check in (also, it's suddenly July)

### ISSUE THREAD

**Issue by emgollie** [mozilla/mozbadging#37]
A few updates on this end:
- Have been working with @zzzndr @andrewhayward on the updated sitemap: https://github.com/mozilla/mozbadging/issues/18
- @zzzndr and I are creating a single list of badges.m.o. page wireframes for easy findability here: https://openbadges.etherpad.mozilla.org/badges-mozilla-org-wireframes
- Eager to get thoughts on this draft schedule looking towards site revamp:
- [ ] Complete first round wireframes (including FAQ and tag pages) by 8 July team meeting
- [ ] Conduct user testing on wireframes weeks of 7 and 14 July (also assess technical feasibility with @andrewhayward @christensenep)
- [ ] Assess user feedback and integrate into mockups for 22 July team meeting
- [ ] Issuer and earner flow technical integration week of 21 July
- [ ] Additional page integration week of 28 July

Also, Erik and I will be OOO for the 4 July (or July 4) holiday. I'll be taking my birthday off next Tuesday, but please proceed with the team meeting in my absence and I'll be checking in with everyone.

Over to you for updates @christensenep @adamlofting @andrewhayward @christensenep.

**Comment by emgollie** [comment]
Friendly check in for updates @adamlofting @andrewhayward @christensenep.

I'll be away tomorrow but @zzzndr will be showing new wireframes per https://openbadges.etherpad.mozilla.org/badges-mozilla-org-wireframes. cc @davidascher

**Comment by andrewhayward** [comment]
At some point I might remember to do this before the start of the next week.
- Put in a request for Mozillians API access; no response yet.
- Sorted out VPN access (haven't had to use it since before the new system was put in place).
- Am able to see badges chief boxes; yet to see if access codes as provided by @lmorchard actually work.
- Various updates to badge studio.
- Discussed various bits and pieces with @zzzndr, and went over subsequent wireframes.

**Comment by zzzndr** [comment]
Spent last week creating a set of wireframes with the aid of @emgollie  & @andrewhayward (:

**Comment by adamlofting** [comment]
No new updates from me this week.

**Comment by ghost** [comment]
- Set up an S3 bucket for our heroku instance at bmo.herokuapp.com (this lets image uploads persist for longer than ten minutes, and makes the badge studio actually work).
- Worked on badge awards, should be live (in staging) later today
