### ISSUE TITLE
Create a draft roadmap to present at next "Now" MoFo call

### ISSUE THREAD

**Issue by davidascher** [mozilla/mozbadging#4]
Assigning to @emgollie but I expect everyone to help shape it.

**Comment by emgollie** [comment]
This currently lives at https://github.com/mozilla/contribubadger/blob/master/roadmap.md and we will continue to edit. cc @christensenep @andrewhayward

**Comment by emgollie** [comment]
Revised at https://github.com/mozilla/mozbadging/wiki/Summer-Roadmap. Please let me know your feedback @christensenep @andrewhayward @davidascher @adamlofting and we will create issues for anything that isn't reflected in this repo yet.

**Comment by adamlofting** [comment]
FWIW, I noticed today that the bugzilla team also use "b.m.o." so we might be best to avoid that to reduce the confusion. :)

**Comment by davidascher** [comment]
right.  badges.m.o it is.

**Comment by emgollie** [comment]
Good catch and revised. Please let me know if you have other feedback on the roadmap and we'll start to socialize it.

**Comment by emgollie** [comment]
Quick update on this: @christensenep is reviewing and adding a few roadmap-related issues, and I'm preparing a note for the Community Builders list and Grow Mozilla meeting to be distributed soon. I know they're eager for our update (I shared the working roadmap with Larissa Shapiro this week and she was excited about the plan.)

**Comment by adamlofting** [comment]
With the caveat that that they were getting a sneak preview, I pointed the CBT systems and data group to this on their call today to give them a sense of where it's headed. Larissa was on the call too and talked about the roadmap.

**Comment by emgollie** [comment]
👍 @adamlofting

**Comment by emgollie** [comment]
I'm getting ready to send an internal email and CBT group update with the roadmap plans, and please forward it to people I've missed who may be interested. Thanks all.
